---
- hosts: all
  gather_facts: yes
  roles:
    - nginx
- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default

- name: Create NGINX Conf File For nodejs
  become: yes
  file:
    path: /etc/nginx/sites-available/nodejs.conf
    state: touch
  
- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/nodejs.conf
      marker: ""
      block: |
        server {
            listen 80;
            location / {
                proxy_pass http://192.168.28.72:5601;
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
        }
- name: Link NGINX nodejs Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/nodejs.conf /etc/nginx/sites-enabled/nodejs.conf

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
